-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE INDEX vozos_gin_idx ON vozos
-- USING GIN ((title || ' ' || description || ' ' || tags || ' ' || reactions) gin_trgm_ops);
